// @vitest-environment jsdom
import { afterEach,beforeEach,expect,it,vi } from "vitest";
import { cleanup,fireEvent,render,screen,waitFor } from "@testing-library/react";
import TaskDetail from "./TaskDetail";
import type { Task } from "../../db/repositories/taskRepository";
const mocks=vi.hoisted(() => ({ tasks:[] as Task[], selectedTaskId:null as number|null, getTask:vi.fn(), getChildren:vi.fn(), updateTask:vi.fn(), load:vi.fn(), completeTask:vi.fn(),cancelTask:vi.fn(),deleteTask:vi.fn(),openEdit:vi.fn(),openTaskDetail:vi.fn(),toggleComplete:vi.fn() }));
vi.mock("../../stores/taskStore",() => ({ useTaskStore:Object.assign((select:(s:unknown)=>unknown) => select(mocks),{ getState:()=>mocks }),taskService:mocks }));
vi.mock("../../stores/goalStore",()=>({ useGoalStore:(select:(s:unknown)=>unknown)=>select({ goals:[] }) }));
vi.mock("../../stores/projectStore",()=>({ useProjectStore:(select:(s:unknown)=>unknown)=>select({ projects:[] }) }));
vi.mock("../../hooks/useTaskFocusStats",()=>({ useTaskFocusStats:()=>({ totalSeconds:900,count:2,completedCount:1 }) }));
vi.mock("../../extensions/host",()=>({ useEnabledTaskActions:()=>[],ExtensionErrorBoundary:()=>null }));
vi.mock("../../features/focus/FocusController",()=>({ StartFocusButton:()=> <button>开始专注</button> }));
vi.mock("./TaskPlanningRange",()=>({ default:()=>null }));
let nextId=100;
function task(id:number,title="任务"):Task { return { id,title,status:"TODO",categoryId:null,estimatedDuration:1800,plannedStart:null,plannedEnd:null,actualDuration:0,scheduledDate:"",createdAt:1,updatedAt:1,completedAt:null,notes:"完成标准",sortOrder:0,goalId:null,projectId:null,parentId:null,courseId:null,priority:"medium",repeatRule:"" }; }
beforeEach(()=>{ vi.clearAllMocks(); mocks.tasks=[task(nextId++)]; mocks.selectedTaskId=mocks.tasks[0].id; Object.assign(mocks,{ categories:[] }); mocks.getChildren.mockResolvedValue([]); mocks.load.mockResolvedValue(undefined); mocks.updateTask.mockImplementation(async (id,input) => ({ ...mocks.tasks.find((t)=>t.id===id),...input,updatedAt:2 })); });
afterEach(cleanup);
it("loads an unplanned task by ID without changing its date",async()=>{ const row=task(777,"未来事项"); mocks.tasks=[]; mocks.selectedTaskId=777; mocks.getTask.mockResolvedValue(row); render(<TaskDetail/>); expect(await screen.findByText("未来事项")).toBeTruthy(); expect(mocks.updateTask).not.toHaveBeenCalled(); });
it("shows a useful empty state",()=>{ mocks.selectedTaskId=null; render(<TaskDetail/>); expect(screen.getByText(/点击左侧任务/)).toBeTruthy(); });
it("saves title, notes and date explicitly with the observed version",async()=>{ render(<TaskDetail/>); fireEvent.click(screen.getByRole("button",{ name:"编辑详情" })); fireEvent.change(screen.getByLabelText("任务名称"),{ target:{ value:"新标题" } }); fireEvent.change(screen.getByLabelText("说明与完成标准"),{ target:{ value:"第一稿" } }); fireEvent.change(screen.getByLabelText("日安排"),{ target:{ value:"2026-10-10" } }); expect(mocks.updateTask).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole("button",{ name:"保存详情" })); await waitFor(()=>expect(mocks.updateTask).toHaveBeenCalledWith(mocks.selectedTaskId,expect.objectContaining({ title:"新标题",notes:"第一稿",scheduledDate:"2026-10-10",plannedStart:null,plannedEnd:null }),1)); });
it("keeps a failed save as a draft",async()=>{ mocks.updateTask.mockRejectedValue(new Error("版本冲突，草稿保留")); render(<TaskDetail/>); fireEvent.click(screen.getByRole("button",{ name:"编辑详情" })); fireEvent.change(screen.getByLabelText("说明与完成标准"),{ target:{ value:"保留输入" } }); fireEvent.click(screen.getByRole("button",{ name:"保存详情" })); await screen.findByText(/版本冲突/); expect((screen.getByLabelText("说明与完成标准") as HTMLTextAreaElement).value).toBe("保留输入"); });
it("keeps task drafts isolated when selection changes",()=>{ const first=mocks.tasks[0],second=task(nextId++,"第二项"); mocks.tasks.push(second); const view=render(<TaskDetail/>); fireEvent.click(screen.getByRole("button",{ name:"编辑详情" })); fireEvent.change(screen.getByLabelText("说明与完成标准"),{ target:{ value:"第一项草稿" } }); mocks.selectedTaskId=second.id; view.rerender(<TaskDetail/>); expect(screen.getByText("完成标准")).toBeTruthy(); mocks.selectedTaskId=first.id; view.rerender(<TaskDetail/>); expect((screen.getByLabelText("说明与完成标准") as HTMLTextAreaElement).value).toBe("第一项草稿"); expect(mocks.updateTask).not.toHaveBeenCalled(); });
it("loads children outside today's list and directs focus to execution tasks",async()=>{ mocks.getChildren.mockResolvedValue([{ ...task(nextId++,"跨日子任务"),parentId:mocks.selectedTaskId }]); render(<TaskDetail/>); await screen.findByText("跨日子任务"); expect(screen.queryByRole("button",{ name:"开始专注" })).toBeNull(); fireEvent.click(screen.getByRole("button",{ name:"跨日子任务" })); expect(mocks.openTaskDetail).toHaveBeenCalled(); });
it("expands the same editor while preserving the draft",()=>{ render(<TaskDetail/>); fireEvent.click(screen.getByRole("button",{ name:"编辑详情" })); fireEvent.change(screen.getByLabelText("说明与完成标准"),{ target:{ value:"展开后保留" } }); fireEvent.click(screen.getByRole("button",{ name:"展开详情" })); expect(screen.getByRole("dialog")).toBeTruthy(); expect((screen.getByLabelText("说明与完成标准") as HTMLTextAreaElement).value).toBe("展开后保留"); });
